name: fyp_healthcare_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/adaptive_icon_foreground.png"
  adaptive_icon_foreground: "assets/adaptive_icon_foreground.png"
  adaptive_icon_background: "assets/adaptive_icon_background.png"

flutter:
  uses-material-design: true
