name: fyp_healthcare_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  google_fonts: ^6.1.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/adaptive_icon_foreground.png"
  adaptive_icon_foreground: "assets/adaptive_icon_foreground.png"
  adaptive_icon_background: "assets/adaptive_icon_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/splash_background.jpg
    - assets/loading_lottie.json
  fonts:
    - family: ProtestRiot
      fonts:
        - asset: fonts\ProtestRiot-Regular.ttf
