name: fyp_healthcare_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  liquid_swipe: ^3.1.0
  http: ^1.2.1
  sqflite: ^2.3.2
  file_picker: ^6.2.0
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  fluttertoast: 8.1.0
  flutter_blue_plus: ^1.31.16
  permission_handler: ^11.3.0
  babstrap_settings_screen: 0.1.6
  workmanager: ^0.5.2
  syncfusion_flutter_gauges: ^25.1.38
  glassmorphism: ^3.0.0
  giffy_dialog: ^2.1.0
  persistent_bottom_nav_bar_v2: ^5.2.2
  alarm: ^3.1.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^25.1.42+1
  select_dialog: ^2.0.1
  flutter_easyloading: ^3.0.5
  bottom_sheet: ^4.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/adaptive_icon_foreground.png"
  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
  adaptive_icon_background: "assets/icon/adaptive_icon_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/icon/
    - assets/lottie/
    - assets/gif/
    - assets/image/
    - assets/audio/
  fonts:
    - family: ProtestRiot
      fonts:
        - asset: fonts\ProtestRiot-Regular.ttf
    - family: PatuaOne
      fonts:
        - asset: fonts\PatuaOne-Regular.ttf
